/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.robinzon.buscarsunat.vista;

import com.robinzon.buscarsunat.Dashboard;
import com.robinzon.buscarsunat.controller.SunatController;
import com.robinzon.buscarsunat.modelo.Empresa;
import com.robinzon.buscarsunat.modelo.Persona;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Matteo
 */
public class jdEspera extends javax.swing.JDialog {

    private String tipoDocu;
    private String numDocu;
    private Dashboard dashboard;
    
    public jdEspera(Dashboard parent, boolean modal, String tipoDocu, String numDocu ) {
        super(parent, modal);
        this.dashboard = parent;
        initComponents();
        this.tipoDocu = tipoDocu;
        this.numDocu = numDocu;
        lblTituloEspera.setText("Buscando "+this.numDocu+" en RENIEC");
        jbEspera.setIndeterminate(true);
        // Configurar comportamiento al cerrar
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); // Evitar que el usuario cierre manualment
        this.carga();
    }
    
    public jdEspera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //this.carga();
    }
    
    private void carga() {
        
        // Ejecutar la consulta en un hilo separado
    new Thread(() -> {
        SunatController objSunatCon;
        
        try {
            if(this.tipoDocu.equalsIgnoreCase("RUC")) {
                objSunatCon = new SunatController();
                Empresa objEmpresa = objSunatCon.consultarRuc(this.numDocu);
                
                // Actualizar la UI en el EDT
                SwingUtilities.invokeLater(() -> {
                    if(objEmpresa != null) {
                        dashboard.mostrarResultado(tipoDocu, objEmpresa, null);
                    } else {
                        JOptionPane.showMessageDialog(this, 
                            "No se encontraron resultados", 
                            "Información", 
                            JOptionPane.INFORMATION_MESSAGE);
                    }
                    this.dispose(); // Cerrar el diálogo
                });
            } else {
                objSunatCon = new SunatController();
                Persona objPersona = objSunatCon.consultarDni(this.numDocu);
                
                SwingUtilities.invokeLater(() -> {
                    if(objPersona != null) {
                        dashboard.mostrarResultado(tipoDocu, null, objPersona);
                    } else {
                        JOptionPane.showMessageDialog(this, 
                            "No se encontraron resultados", 
                            "Información", 
                            JOptionPane.INFORMATION_MESSAGE);
                    }
                    this.dispose(); // Cerrar el diálogo
                });
            }
        } catch (Exception e) {
            SwingUtilities.invokeLater(() -> {
                JOptionPane.showMessageDialog(this, 
                    "Error al consultar: " + e.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                this.dispose(); // Cerrar el diálogo en caso de error
            });
        }
    }).start();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jpPrincipal = new javax.swing.JPanel();
        lblIconoEspera = new javax.swing.JLabel();
        lblTituloEspera = new javax.swing.JLabel();
        jbEspera = new javax.swing.JProgressBar();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblIconoEspera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconoEspera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viaje-de-negocios.png"))); // NOI18N

        lblTituloEspera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloEspera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloEspera.setText("Buscando documento en RENIEC");

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloEspera, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addComponent(lblIconoEspera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEspera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)))
                .addGap(0, 0, 0))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloEspera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconoEspera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbEspera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdEspera dialog = new jdEspera(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JProgressBar jbEspera;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JLabel lblIconoEspera;
    private javax.swing.JLabel lblTituloEspera;
    // End of variables declaration//GEN-END:variables
}
